### PR TITLE
Bugfix/#126

### LINKED ISSUE #126: acts_as_context not working
#### Current Behavior

calling `acts_as_context` on an `ActiveRecord` model raises `NameError`

#### Expected Behavior

calling `acts_as_context` on an `ActiveRecord` model should not raise `NameError` and should include the appropriate context methods on the model.
 
#### Steps to Reproduce

1. Create an `ActiveRecord` class
2. Call `acts_as_context` on that class
```ruby
class Model < ApplicationRecord
  acts_as_context
end
```
3. go into rails console `rails c`
4. try `Model.new`

#### Additional Comments

It would appear [this initializer](https://github.com/aaronmallen/activeinteractor/blob/master/lib/active_interactor/rails/railtie.rb#L17) is either never invoked or is invoked after `ActiveSupport.run_load_hooks` is called for `ActiveRecord`. This could be an issue with the gem name not properly loading things in the path when rails is looking for `Railties`.  

It should also be noted that if you go into rails console and run:
```ruby
ActiveSupport.run_load_hooks(:active_record_base, ActiveRecord::Base)
```
`acts_as_context` works as expected.

### PR DESCRIPTION
**Pull request by aaronmallen**
## Description

Fixes an issue with `ActiveRecord` helper methods not loading

## Information

- [x] Contains Documentation
- [x] Contains Tests
- [ ] Contains Breaking Changes

## Related Issues

- fixes #126

### Added

- `ActiveInteractor::Rails::Models`

### Removed

- `ActiveInteractor::Rails::ActiveRecord`

### Fixed

- #126 `act_as_context` not working

### CODE REVIEW

**Comment by aaronmallen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- lib/active_interactor/rails/models.rb  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aaronmallen/activeinteractor/pullRequest?prid=4858256&bid=16118586)

File: lib/active_interactor/rails/models.rb [hunk 1]
```diff
@@ -27,19 +20,21 @@ def acts_as_context
...
-        def initialize(context = nil, options = {})
-          copy_flags!(context) if context
-          copy_called!(context) if context
-          attributes = context.to_h if context
-          super(attributes, options)
+        # @param attributes [Hash|nil] attributes to assign to the class
+        def initialize(attributes = nil)
+          copy_flags!(attributes) if attributes
+          copy_called!(attributes) if attributes
+          attributes_as_hash = attributes && attributes.respond_to?(:to_h) ? attributes.to_h : attributes.attributes&.to_h
```
Comment (aaronmallen) [inline lib/active_interactor/rails/models.rb]: Codacy Issue found: [Line is too long. [122/120]](https://app.codacy.com/manual/aaronmallen/activeinteractor/pullRequest?prid=4858256)

Comment (aaronmallen) [inline lib/active_interactor/rails/models.rb]: Codacy Issue found: [Use safe navigation (`&.`) instead of checking if an object exists before calling the method.](https://app.codacy.com/manual/aaronmallen/activeinteractor/pullRequest?prid=4858256)

**Comment by aaronmallen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/active_interactor/rails/models.rb  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aaronmallen/activeinteractor/pullRequest?prid=4858256&bid=16118586)

**Comment by aaronmallen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/active_interactor/rails/models.rb  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aaronmallen/activeinteractor/pullRequest?prid=4858256&bid=16118586)
